package pnm

import (
	"fmt"
	"strings"
)

// GenTB generates tb_pnm.v — a self-checking Verilog testbench for pnm_top —
// ported byte-for-byte from sim/gen_tb.py.
//
// The testbench is the pure-Verilog half of the co-simulation contract:
//
//   - the tb reads the injection program from stimulus.hex ($readmemh) and
//     streams it into the real fabric with valid/ready flow control at up to
//     1 byte/cycle (Paper.MD §2.8: one routing decision per clock)
//   - every node DMA sink applies deterministic backpressure (ready one cycle
//     in N), proving the fabric is lossless, not dropping
//   - every byte the fabric delivers — node DMA ports, spine tail, and the
//     X/Y-lane residual lanes — is logged to delivery.log, stamped with the
//     simulation cycle, so the harness can verify byte-exact delivery, run
//     the virtual execution units, and check per-packet latency against the
//     paper's closed-form bound (§2.5, §3.4)
//
// Simulation stops adaptively when the fabric has been quiet for 200 cycles,
// so no fixed drain window has to be tuned by hand.
//
// layerIDs must match the pnm_top.v under test (a sub-list = one slice of a
// chassis partitioned by RunOne with groups > 1). stim/log are the
// $readmemh / $fopen file names, parameterized so parallel groups never
// share files.
func GenTB(layerIDs []int, bx, by int, bp map[NodeID]int, nbytes int, stim, log string) string {
	var out strings.Builder
	a := func(s string) { out.WriteString(s + "\n") }

	a("`timescale 1ns/1ps")
	a("`include \"pnm_defs.vh\"")
	a("")
	a("// AUTO-GENERATED by sim/internal/pnm/gen_tb.go -- do not edit by hand.")
	a(fmt.Sprintf("// layers=%s  board_x=%d  board_y=%d", pyIntList(layerIDs), bx, by))
	a("//")
	a("// Pure-Verilog co-simulation harness for pnm_top.v:")
	a("//   * stimulus.hex ($readmemh) -> injector task -> real fabric")
	a("//   * per-node backpressure (ready 1 cycle in N) -> losslessness")
	a("//   * delivery.log records every node DMA / tail / residual byte")
	a("//   * $finish when the fabric has been quiet for 200 cycles")
	a("module tb_pnm;")
	a("")
	a("    // -- clock / reset -------------------------------------------")
	a("    reg clk = 1'b0;")
	a("    always #5 clk = ~clk; // 100 MHz")
	a("    reg rst_n = 1'b0;")
	a("")
	a("    // -- spine inject ---------------------------------------------")
	a("    reg  [7:0] inject_data = 8'h00;")
	a("    reg        inject_valid = 1'b0;")
	a("    reg        inject_sop = 1'b0;")
	a("    reg        inject_eop = 1'b0;")
	a("    wire       inject_ready;")
	a("    reg  [1:0] inject_vc_reg = 2'b10;")
	a("    wire [1:0] inject_vc = inject_vc_reg; // default class 2 (spine descent)")
	a("")
	a("    // -- free-running cycle counter (timestamps delivery.log) ---")
	a("    reg  [31:0] cyc = 32'd0;")
	a("    always @(posedge clk) cyc <= cyc + 32'd1;")
	a("")
	a("    // -- spine tail / residual lanes ------------------------------")
	a("    wire [7:0] tail_data;  wire tail_valid, tail_sop, tail_eop;")
	a("    wire [1:0] tail_vc;  wire [1:0] tail_up_vc;")
	a("    wire [7:0] tail_up_data; wire tail_up_valid, tail_up_sop, tail_up_eop;")
	for _, l := range layerIDs {
		a(fmt.Sprintf("    wire [7:0] xres_%d_data;  wire xres_%d_valid, xres_%d_sop, xres_%d_eop;", l, l, l, l))
		for x := 0; x < bx; x++ {
			a(fmt.Sprintf("    wire [7:0] yres_%d_%d_data;  wire yres_%d_%d_valid, yres_%d_%d_sop, yres_%d_%d_eop;", l, x, l, x, l, x, l, x))
		}
	}
	a("")
	a("    // -- node DMA ports -------------------------------------------")
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				p := fmt.Sprintf("node_%d_%d_%d", l, x, y)
				a(fmt.Sprintf("    wire [7:0] %s_data;  wire %s_valid, %s_sop, %s_eop;  reg %s_ready;", p, p, p, p, p))
				a(fmt.Sprintf("    wire node_corrupt_%d_%d_%d;  // MAC stub doorbell verdict", l, x, y))
				a(fmt.Sprintf("    wire [1:0] node_vc_%d_%d_%d;  // on-board class (3)", l, x, y))
			}
		}
	}
	a("")
	a("    // -- DUT: the paper-mirroring topology ------------------------")
	a("    pnm_top dut (")
	a("        .clk(clk), .rst_n(rst_n),")
	a("        .inject_data(inject_data), .inject_valid(inject_valid),")
	a("        .inject_sop(inject_sop), .inject_eop(inject_eop), .inject_ready(inject_ready),")
	a("        .inject_vc(inject_vc),")
	a("        .tail_data(tail_data), .tail_valid(tail_valid),")
	a("        .tail_sop(tail_sop), .tail_eop(tail_eop), .tail_vc(tail_vc),")
	a("        .tail_up_data(tail_up_data), .tail_up_valid(tail_up_valid),")
	a("        .tail_up_sop(tail_up_sop), .tail_up_eop(tail_up_eop), .tail_up_vc(tail_up_vc),")
	var conn []string
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				p := fmt.Sprintf("node_%d_%d_%d", l, x, y)
				conn = append(conn, fmt.Sprintf("        .%s_data(%s_data), .%s_valid(%s_valid), .%s_sop(%s_sop), .%s_eop(%s_eop), .%s_ready(%s_ready),", p, p, p, p, p, p, p, p, p, p))
				conn = append(conn, fmt.Sprintf("        .node_corrupt_%d_%d_%d(node_corrupt_%d_%d_%d),", l, x, y, l, x, y))
				conn = append(conn, fmt.Sprintf("        .node_vc_%d_%d_%d(node_vc_%d_%d_%d),", l, x, y, l, x, y))
			}
		}
	}
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			conn = append(conn, fmt.Sprintf("        .yres_%d_%d_data(yres_%d_%d_data), .yres_%d_%d_valid(yres_%d_%d_valid), .yres_%d_%d_sop(yres_%d_%d_sop), .yres_%d_%d_eop(yres_%d_%d_eop),", l, x, l, x, l, x, l, x, l, x, l, x, l, x, l, x))
		}
	}
	for _, l := range layerIDs {
		conn = append(conn, fmt.Sprintf("        .xres_%d_data(xres_%d_data), .xres_%d_valid(xres_%d_valid), .xres_%d_sop(xres_%d_sop), .xres_%d_eop(xres_%d_eop),", l, l, l, l, l, l, l, l))
	}
	conn[len(conn)-1] = strings.TrimRight(conn[len(conn)-1], ",")
	a(strings.Join(conn, "\n"))
	a("    );")
	a("")
	a("    // -- per-node backpressure: ready 1 cycle in N ----------------")
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				d := 1
				if v, ok := bp[NodeID{L: l, X: x, Y: y}]; ok {
					d = v
				}
				p := fmt.Sprintf("node_%d_%d_%d", l, x, y)
				a(fmt.Sprintf("    reg [3:0] bpctr_%d_%d_%d;", l, x, y))
				a(fmt.Sprintf("    always @(posedge clk or negedge rst_n)"))
				a(fmt.Sprintf("        if (!rst_n) bpctr_%d_%d_%d <= 4'd0;", l, x, y))
				a(fmt.Sprintf("        else         bpctr_%d_%d_%d <= bpctr_%d_%d_%d + 4'd1;", l, x, y, l, x, y))
				a(fmt.Sprintf("    always @(*) %s_ready = (bpctr_%d_%d_%d %% 4'd%d == 4'd0);", p, l, x, y, d))
			}
		}
	}
	a("")
	a("    // -- delivery log (cycle-stamped, VC sideband) ---------------")
	a("    integer fd;")
	a(fmt.Sprintf("    initial fd = $fopen(\"%s\", \"w\");", log))
	a("    always @(posedge clk)")
	a("        if (inject_valid && inject_ready)")
	a("            $fwrite(fd, \"I %0d %0d %0d %0d %0d\\n\", cyc, inject_data, inject_sop, inject_eop, inject_vc);")
	for _, l := range layerIDs {
		a("    always @(posedge clk)")
		a(fmt.Sprintf("        if (xres_%d_valid)", l))
		a(fmt.Sprintf("            $fwrite(fd, \"X %%0d %d %%0d %%0d %%0d\\n\", cyc, xres_%d_data, xres_%d_sop, xres_%d_eop);", l, l, l, l))
		for x := 0; x < bx; x++ {
			a("    always @(posedge clk)")
			a(fmt.Sprintf("        if (yres_%d_%d_valid)", l, x))
			a(fmt.Sprintf("            $fwrite(fd, \"Y %%0d %d %d %%0d %%0d %%0d\\n\", cyc, yres_%d_%d_data, yres_%d_%d_sop, yres_%d_%d_eop);", l, x, l, x, l, x, l, x))
		}
	}
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				p := fmt.Sprintf("node_%d_%d_%d", l, x, y)
				a("    always @(posedge clk)")
				a(fmt.Sprintf("        if (%s_valid && %s_ready)", p, p))
				a(fmt.Sprintf("            $fwrite(fd, \"N %%0d %d %d %d %%0d %%0d %%0d %%0d\\n\", cyc, %s_data, %s_sop, %s_eop, node_vc_%d_%d_%d);", l, x, y, p, p, p, l, x, y))
				a("    always @(posedge clk)")
				a(fmt.Sprintf("        if (node_corrupt_%d_%d_%d)", l, x, y))
				a(fmt.Sprintf("            $fwrite(fd, \"C %%0d %d %d %d\\n\", cyc);", l, x, y))
			}
		}
	}
	a("    always @(posedge clk)")
	a("        if (tail_valid)")
	a("            $fwrite(fd, \"T %0d %0d %0d %0d %0d\\n\", cyc, tail_data, tail_sop, tail_eop, tail_vc);")
	a("    always @(posedge clk)")
	a("        if (tail_up_valid)")
	a("            $fwrite(fd, \"U %0d %0d %0d %0d %0d\\n\", cyc, tail_up_data, tail_up_sop, tail_up_eop, tail_up_vc);")
	a("")
	a("    // -- injection program ($readmemh) ----------------------------")
	a(fmt.Sprintf("    parameter integer NBYTES = %d;", nbytes))
	a("    // stim[i][7:0] = byte, [8] = sop, [9] = eop, [11:10] = vc")
	a("    reg [11:0] stim [0:(NBYTES > 0 ? NBYTES : 1)-1];")
	a(fmt.Sprintf("    initial $readmemh(\"%s\", stim);", stim))
	a("")
	a("    // Streaming injector: sustains 1 byte/cycle while the fabric")
	a("    // accepts (Paper.MD §2.8: one routing decision per clock).  Drive")
	a("    // at negedge, handshake at posedge; when !ready the byte is held.")
	a("    task inject_stream;")
	a("        integer i;")
	a("        begin")
	a("            i = 0;")
	a("            @(negedge clk);")
	a("            while (i < NBYTES) begin")
	a("                inject_data  = stim[i][7:0];")
	a("                inject_sop   = stim[i][8];")
	a("                inject_eop   = stim[i][9];")
	a("                inject_vc_reg = stim[i][11:10];")
	a("                inject_valid = 1'b1;")
	a("                @(posedge clk);")
	a("                if (inject_ready) i = i + 1;")
	a("                @(negedge clk);")
	a("            end")
	a("            inject_valid = 1'b0; inject_sop = 1'b0; inject_eop = 1'b0;")
	a("        end")
	a("    endtask")
	a("")
	a("    // -- adaptive termination --------------------------------------")
	a("    wire any_valid = inject_valid || tail_valid || tail_up_valid")
	for _, l := range layerIDs {
		a(fmt.Sprintf("                    || xres_%d_valid", l))
		for x := 0; x < bx; x++ {
			a(fmt.Sprintf("                    || yres_%d_%d_valid", l, x))
		}
	}
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				a(fmt.Sprintf("                    || node_%d_%d_%d_valid", l, x, y))
			}
		}
	}
	a("                    ;")
	a("")
	a("    reg inject_finished = 1'b0;")
	a("    reg [31:0] quiet = 32'd0;")
	a("    always @(posedge clk or negedge rst_n)")
	a("        if (!rst_n)          quiet <= 32'd0;")
	a("        else if (any_valid)  quiet <= 32'd0;")
	a("        else if (inject_finished) quiet <= quiet + 32'd1;")
	a("")
	a("    // ==============================================================")
	a("    initial begin")
	a("        repeat (5) @(negedge clk);")
	a("        rst_n = 1'b1;")
	a("        repeat (3) @(negedge clk);")
	a("")
	a("        inject_stream();")
	a("        inject_finished = 1'b1;")
	a("    end")
	a("")
	a("    initial begin")
	a("        wait (inject_finished === 1'b1);")
	a("        while (quiet < 32'd200) @(posedge clk);")
	a("        $fclose(fd);")
	a("        $display(\"=== SIM COMPLETE (quiet=%0d cycles) ===\", quiet);")
	a("        $finish;")
	a("    end")
	a("")
	a("    initial begin")
	a("        repeat (64 * NBYTES + 1000000) @(negedge clk); // adaptive watchdog")
	a("        $display(\"=== WATCHDOG TIMEOUT ===\");")
	a("        $fclose(fd);")
	a("        $finish;")
	a("    end")
	a("")
	a("endmodule")
	return out.String()
}
