package pnm

import (
	"fmt"
	"strings"
)

// GenTopology generates pnm_top.v — the paper topology wired from the HDL
// fabric blocks — ported byte-for-byte from sim/gen_topology.py.
//
// Mirrors Paper.MD §2.1–2.2:
//
//   - a single vertical spine of xyz_repeater gates (LAYER_ID compare), each
//     stage HFR-repeatered
//   - a thin X/Y board per layer, hung off the spine via the repeater NoB port
//   - dimension-order on-board routing: an X-lane of xy_turn gates; every
//     column drops onto a Y-lane of node_eject gates
//   - every (layer, x, y) node DMA port is exposed so the virtual execution
//     units can attach to the real hardware
//   - the reverse (egress) path: node TX echoes merge up the board (vc_merge
//     trees) into the spine ascent, each stage HFR-repeatered, exiting at the
//     chassis root (tail_up)
//   - the 2-bit VC sideband (paper §4.3) rides every link: class 2 on the
//     spine descent, 2->3 at the repeater attachment, class 0 on board
//     egress, 0->1 at the up-spine merge
//   - optional KV cache banks per layer (paper §2.6, §3.3): when kvcache is
//     true, a kv_cache_bank sits between each xyz_repeater's NoB output and
//     the first xy_turn gate, providing per-layer FIFO KV storage with
//     offload/reclaim interfaces tied off (active control via kv_offload.v)
//
// layerIDs: global (0-based) layer numbers to instantiate, in spine order.
// A sub-list generates a horizontal slice of the chassis — used by RunOne
// with groups > 1 to simulate layer groups in parallel vvp processes.
// biases: {(layer, x, y): bias_add constant} for each node's MAC stub.
// kvcache: when true, instantiate kv_cache_bank between NoB and xy_turn per layer.
func GenTopology(layerIDs []int, bx, by int, biases map[NodeID]int, kvcache bool) string {
	if biases == nil {
		biases = map[NodeID]int{}
	}
	var out strings.Builder
	a := func(s string) { out.WriteString(s + "\n") }
	nodes := len(layerIDs) * bx * by

	// -- port list ------------------------------------------------------
	var ports []string
	ports = append(ports,
		"    input  wire       clk,",
		"    input  wire       rst_n,",
		"",
		"    // -- spine injection (AOT compiler / scheduler) ------------",
		"    input  wire [7:0] inject_data,",
		"    input  wire       inject_valid,",
		"    input  wire       inject_sop,",
		"    input  wire       inject_eop,",
		"    output wire       inject_ready,",
		"    input  wire [1:0] inject_vc,        // class 2: spine descent",
		"",
		"    // -- spine tail (non-local traffic passes straight through) -",
		"    output wire [7:0] tail_data,",
		"    output wire       tail_valid,",
		"    output wire       tail_sop,",
		"    output wire       tail_eop,",
		"    output wire [1:0] tail_vc,",
		"",
		"    // -- spine root egress (result echoes, class 1 ascent) -----",
		"    output wire [7:0] tail_up_data,",
		"    output wire       tail_up_valid,",
		"    output wire       tail_up_sop,",
		"    output wire       tail_up_eop,",
		"    output wire [1:0] tail_up_vc,",
		"",
		"    // -- node DMA ports (virtual execution units) --------------",
	)
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				p := fmt.Sprintf("node_%d_%d_%d", l, x, y)
				ports = append(ports,
					fmt.Sprintf("    output wire [7:0] %s_data,", p),
					fmt.Sprintf("    output wire       %s_valid,", p),
					fmt.Sprintf("    output wire       %s_sop,", p),
					fmt.Sprintf("    output wire       %s_eop,", p),
					fmt.Sprintf("    input  wire       %s_ready,", p),
					fmt.Sprintf("    output wire       node_corrupt_%d_%d_%d,", l, x, y),
					fmt.Sprintf("    output wire [1:0] node_vc_%d_%d_%d,", l, x, y),
				)
			}
		}
	}
	ports = append(ports,
		"",
		"    // -- board residual lanes (must stay empty) ----------------",
		"    //    yres_<l>_<x> : tail of column x's Y-lane after last row",
	)
	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			ports = append(ports,
				fmt.Sprintf("    output wire [7:0] yres_%d_%d_data,", l, x),
				fmt.Sprintf("    output wire       yres_%d_%d_valid,", l, x),
				fmt.Sprintf("    output wire       yres_%d_%d_sop,", l, x),
				fmt.Sprintf("    output wire       yres_%d_%d_eop,", l, x),
			)
		}
	}
	ports = append(ports, "    //    xres_<l> : tail of board l's X-lane after last column")
	for _, l := range layerIDs {
		ports = append(ports,
			fmt.Sprintf("    output wire [7:0] xres_%d_data,", l),
			fmt.Sprintf("    output wire       xres_%d_valid,", l),
			fmt.Sprintf("    output wire       xres_%d_sop,", l),
			fmt.Sprintf("    output wire       xres_%d_eop,", l),
		)
	}
	ports[len(ports)-1] = strings.TrimRight(ports[len(ports)-1], ",")

	// -- header ---------------------------------------------------------
	a("`include \"pnm_defs.vh\"")
	a("")
	a("// AUTO-GENERATED by sim/internal/pnm/gen_topology.go -- do not edit by hand.")
	a(fmt.Sprintf("// layers=%s  board_x=%d  board_y=%d  nodes=%d", pyIntList(layerIDs), bx, by, nodes))
	a("//")
	a("// Architecture (Paper.MD §2.1–2.2):")
	a("//   single-spine tree fabric: xyz_repeater (LAYER_ID compare) repeatered by HFR")
	a("//   on-board dimension-order: X-lane of xy_turn gates -> Y-lanes of node_eject")
	a("//   every (layer, x, y) ejects to a node DMA / virtual execution unit port")
	a("//   reverse path: node TX echoes -> vc_merge trees -> spine ascent -> root")
	a("//   VC sideband (§4.3): 2 spine descent, 3 on-board, 0 board egress, 1 ascent")
	a("module pnm_top (")
	a(strings.Join(ports, "\n"))
	a(");")
	a("")
	a("    // ================= spine =================================")
	a("    // each stage: xyz_repeater compares LAYER_ID; HFR repeats the pass path")

	for _, l := range layerIDs {
		a(fmt.Sprintf("    wire [7:0] sp_%d_data;  wire sp_%d_valid, sp_%d_sop, sp_%d_eop, sp_%d_ready; wire [1:0] sp_%d_vc;", l, l, l, l, l, l))
		a(fmt.Sprintf("    wire [7:0] q_%d_data;   wire q_%d_valid,  q_%d_sop,  q_%d_eop,  q_%d_ready;  wire [1:0] q_%d_vc;", l, l, l, l, l, l))
		a(fmt.Sprintf("    wire [7:0] nob_%d_data; wire nob_%d_valid, nob_%d_sop, nob_%d_eop, nob_%d_ready; wire [1:0] nob_%d_vc;", l, l, l, l, l, l))
		a(fmt.Sprintf("    wire [7:0] nobu_%d_data; wire nobu_%d_valid, nobu_%d_sop, nobu_%d_eop, nobu_%d_ready; wire [1:0] nobu_%d_vc;", l, l, l, l, l, l))
		a(fmt.Sprintf("    wire [7:0] spup_%d_data; wire spup_%d_valid, spup_%d_sop, spup_%d_eop, spup_%d_ready; wire [1:0] spup_%d_vc;", l, l, l, l, l, l))
		a(fmt.Sprintf("    wire [7:0] spupi_%d_data; wire spupi_%d_valid, spupi_%d_sop, spupi_%d_eop, spupi_%d_ready; wire [1:0] spupi_%d_vc;", l, l, l, l, l, l))
		a(fmt.Sprintf("    wire [7:0] uph_%d_data;  wire uph_%d_valid,  uph_%d_sop,  uph_%d_eop,  uph_%d_ready;  wire [1:0] uph_%d_vc;", l, l, l, l, l, l))
	}
	a("")

	last := layerIDs[len(layerIDs)-1]
	for pos, l := range layerIDs {
		spin := "inject"
		if pos != 0 {
			spin = fmt.Sprintf("q_%d", layerIDs[pos-1])
		}
		a(fmt.Sprintf("    // -- layer %d repeater (strips LAYER_ID on match) -----------", l))
		a(fmt.Sprintf("    xyz_repeater u_rpt_%d (", l))
		a(fmt.Sprintf("        .route_bitmap(11'h%03x),  // layer %d, X, +, 0", (l+1)<<7, l+1))
		a("        .clk(clk), .rst_n(rst_n),")
		a(fmt.Sprintf("        .spin_data(%s_data), .spin_valid(%s_valid), .spin_sop(%s_sop),", spin, spin, spin))
		a(fmt.Sprintf("        .spin_eop(%s_eop), .spin_ready(%s_ready),", spin, spin))
		if pos == 0 {
			a("        .spin_vc(inject_vc),")
		} else {
			a(fmt.Sprintf("        .spin_vc(q_%d_vc),", layerIDs[pos-1]))
		}
		a(fmt.Sprintf("        .spout_data(sp_%d_data), .spout_valid(sp_%d_valid), .spout_sop(sp_%d_sop),", l, l, l))
		a(fmt.Sprintf("        .spout_eop(sp_%d_eop), .spout_ready(sp_%d_ready),", l, l))
		a(fmt.Sprintf("        .spout_vc(sp_%d_vc),", l))
		a(fmt.Sprintf("        .nob_data(nob_%d_data), .nob_valid(nob_%d_valid), .nob_sop(nob_%d_sop),", l, l, l))
		a(fmt.Sprintf("        .nob_eop(nob_%d_eop), .nob_ready(nob_%d_ready),", l, l))
		a(fmt.Sprintf("        .nob_vc(nob_%d_vc),", l))
		a(fmt.Sprintf("        .nob_up_data(nobu_%d_data), .nob_up_valid(nobu_%d_valid), .nob_up_sop(nobu_%d_sop),", l, l, l))
		a(fmt.Sprintf("        .nob_up_eop(nobu_%d_eop), .nob_up_ready(nobu_%d_ready), .nob_up_vc(nobu_%d_vc),", l, l, l))
		if pos == len(layerIDs)-1 {
			// bottom of the slice: the up-spine ingress from the layer below
			// is outside the chassis partition -> tied off
			a(fmt.Sprintf("        .spup_in_data(spupi_%d_data), .spup_in_valid(spupi_%d_valid), .spup_in_sop(spupi_%d_sop),", l, l, l))
			a(fmt.Sprintf("        .spup_in_eop(spupi_%d_eop), .spup_in_ready(spupi_%d_ready), .spup_in_vc(spupi_%d_vc),", l, l, l))
		} else {
			a(fmt.Sprintf("        .spup_in_data(uph_%d_data), .spup_in_valid(uph_%d_valid), .spup_in_sop(uph_%d_sop),", l, l, l))
			a(fmt.Sprintf("        .spup_in_eop(uph_%d_eop), .spup_in_ready(uph_%d_ready), .spup_in_vc(uph_%d_vc),", l, l, l))
		}
		if pos == 0 {
			a("        .spup_data(tail_up_data), .spup_valid(tail_up_valid), .spup_sop(tail_up_sop),")
			a("        .spup_eop(tail_up_eop), .spup_ready(1'b1), .spup_vc(tail_up_vc)")
		} else {
			a(fmt.Sprintf("        .spup_data(spup_%d_data), .spup_valid(spup_%d_valid), .spup_sop(spup_%d_sop),", l, l, l))
			a(fmt.Sprintf("        .spup_eop(spup_%d_eop), .spup_ready(spup_%d_ready), .spup_vc(spup_%d_vc)", l, l, l))
		}
		a("    );")
		a(fmt.Sprintf("    // -- spine repeater %d --------------------------------------", l))
		a(fmt.Sprintf("    hfr u_sp_hfr_%d (", l))
		a(fmt.Sprintf("        .route_bitmap(11'h%03x),  // layer %d (spine stage)", (l+1)<<7, l+1))
		a("        .clk(clk), .rst_n(rst_n),")
		a(fmt.Sprintf("        .in_data(sp_%d_data), .in_valid(sp_%d_valid), .in_sop(sp_%d_sop),", l, l, l))
		a(fmt.Sprintf("        .in_eop(sp_%d_eop), .in_ready(sp_%d_ready),", l, l))
		a(fmt.Sprintf("        .in_vc(sp_%d_vc),", l))
		a(fmt.Sprintf("        .out_data(q_%d_data), .out_valid(q_%d_valid), .out_sop(q_%d_sop),", l, l, l))
		a(fmt.Sprintf("        .out_eop(q_%d_eop), .out_ready(q_%d_ready),", l, l))
		a(fmt.Sprintf("        .out_vc(q_%d_vc)", l))
		a("    );")
		a("")
	}

	a("    // -- spine tail -----------------------------------------------")
	a(fmt.Sprintf("    assign tail_data  = q_%d_data;", last))
	a(fmt.Sprintf("    assign tail_valid = q_%d_valid;", last))
	a(fmt.Sprintf("    assign tail_sop   = q_%d_sop;", last))
	a(fmt.Sprintf("    assign tail_eop   = q_%d_eop;", last))
	a(fmt.Sprintf("    assign tail_vc    = q_%d_vc;", last))
	a(fmt.Sprintf("    assign q_%d_ready = 1'b1;", last))
	a("")
	a("    // -- spine ascent: bottom layer's ingress is tied off ---------")
	a(fmt.Sprintf("    assign spupi_%d_data = 8'h00; assign spupi_%d_valid = 1'b0;", last, last))
	a(fmt.Sprintf("    assign spupi_%d_sop = 1'b0;   assign spupi_%d_eop = 1'b0;", last, last))
	a(fmt.Sprintf("    assign spupi_%d_vc = 2'b00;", last))
	a("")

	// -- boards ---------------------------------------------------------
	for _, l := range layerIDs {
		a(fmt.Sprintf("    // ================= board %d (layer %d) ==============", l, l+1))
		a("    // dimension-order routing: X first, then Y.")
		for x := 0; x < bx; x++ {
			a(fmt.Sprintf("    wire [7:0] t_%d_%d_data; wire t_%d_%d_valid, t_%d_%d_sop, t_%d_%d_eop, t_%d_%d_ready; wire [1:0] t_%d_%d_vc;", l, x, l, x, l, x, l, x, l, x, l, x))
			a(fmt.Sprintf("    wire [7:0] h_%d_%d_data; wire h_%d_%d_valid, h_%d_%d_sop, h_%d_%d_eop, h_%d_%d_ready; wire [1:0] h_%d_%d_vc;", l, x, l, x, l, x, l, x, l, x, l, x))
			if kvcache {
				a(fmt.Sprintf("    wire [7:0] kvc_%d_%d_data; wire kvc_%d_%d_valid, kvc_%d_%d_sop, kvc_%d_%d_eop, kvc_%d_%d_ready; wire [1:0] kvc_%d_%d_vc;", l, x, l, x, l, x, l, x, l, x, l, x))
			}
			for y := 0; y < by; y++ {
				a(fmt.Sprintf("    wire [7:0] y_%d_%d_%d_data; wire y_%d_%d_%d_valid, y_%d_%d_%d_sop, y_%d_%d_%d_eop, y_%d_%d_%d_ready; wire [1:0] y_%d_%d_%d_vc;", l, x, y, l, x, y, l, x, y, l, x, y, l, x, y, l, x, y))
				// node-eject -> MAC-stub interconnect (DMA stream into the PE)
				a(fmt.Sprintf("    wire [7:0] node_e_%d_%d_%d_data; wire node_e_%d_%d_%d_valid, node_e_%d_%d_%d_sop, node_e_%d_%d_%d_eop, node_e_%d_%d_%d_ready;", l, x, y, l, x, y, l, x, y, l, x, y, l, x, y))
				// node TX echo -> merge-tree interconnect
				a(fmt.Sprintf("    wire [7:0] txe_%d_%d_%d_data; wire txe_%d_%d_%d_valid, txe_%d_%d_%d_sop, txe_%d_%d_%d_eop, txe_%d_%d_%d_ready; wire [1:0] txe_%d_%d_%d_vc;", l, x, y, l, x, y, l, x, y, l, x, y, l, x, y, l, x, y))
			}
			if by > 1 {
				// Y-up merge chain for this column
				for y := 0; y < by-1; y++ {
					a(fmt.Sprintf("    wire [7:0] ym_%d_%d_%d_data; wire ym_%d_%d_%d_valid, ym_%d_%d_%d_sop, ym_%d_%d_%d_eop, ym_%d_%d_%d_ready; wire [1:0] ym_%d_%d_%d_vc;", l, x, y, l, x, y, l, x, y, l, x, y, l, x, y, l, x, y))
				}
			}
		}
		if bx > 1 {
			for x := 0; x < bx-1; x++ {
				a(fmt.Sprintf("    wire [7:0] xm_%d_%d_data; wire xm_%d_%d_valid, xm_%d_%d_sop, xm_%d_%d_eop, xm_%d_%d_ready; wire [1:0] xm_%d_%d_vc;", l, x, l, x, l, x, l, x, l, x, l, x))
			}
		}
		a("")

		for x := 0; x < bx; x++ {
			xin := fmt.Sprintf("nob_%d", l)
			if x != 0 {
				xin = fmt.Sprintf("h_%d_%d", l, x-1)
			}
			if kvcache {
				// KV cache bank: sits between NoB/HFR output and xy_turn input
				a(fmt.Sprintf("    // -- column %d: KV cache bank (paper §2.6, §3.3) ----", x))
				a(fmt.Sprintf("    kv_cache_bank #(.BANK_DEPTH(1024), .ENTRY_BYTES(512)) u_kvc_%d_%d (", l, x))
				a("        .clk(clk), .rst_n(rst_n),")
				a(fmt.Sprintf("        .nob_in_data(%s_data), .nob_in_valid(%s_valid), .nob_in_sop(%s_sop),", xin, xin, xin))
				a(fmt.Sprintf("        .nob_in_eop(%s_eop), .nob_in_ready(%s_ready),", xin, xin))
				a(fmt.Sprintf("        .nob_in_vc(%s_vc),", xin))
				a(fmt.Sprintf("        .nob_out_data(kvc_%d_%d_data), .nob_out_valid(kvc_%d_%d_valid), .nob_out_sop(kvc_%d_%d_sop),", l, x, l, x, l, x))
				a(fmt.Sprintf("        .nob_out_eop(kvc_%d_%d_eop), .nob_out_ready(kvc_%d_%d_ready),", l, x, l, x))
				a(fmt.Sprintf("        .nob_out_vc(kvc_%d_%d_vc),", l, x))
				a("        .kv_store_data(8'h00), .kv_store_valid(1'b0), .kv_store_sop(1'b0), .kv_store_eop(1'b0),")
				a("        .kv_load_ready(1'b0),")
				a("        .evict_req(1'b0), .evict_addr(10'd0), .evict_ready(1'b0),")
				a("        .reclaim_req(1'b0), .reclaim_data(8'h00), .reclaim_valid(1'b0), .reclaim_sop(1'b0), .reclaim_eop(1'b0)")
				a("    );")
				xin = fmt.Sprintf("kvc_%d_%d", l, x)
			}
			a(fmt.Sprintf("    // -- column %d: X->Y turn gate ---------------------------", x))
			a(fmt.Sprintf("    xy_turn #(.LOCAL_X(4'h%x)) u_%d_turn_%d (", x, l, x))
			a("        .clk(clk), .rst_n(rst_n),")
			a(fmt.Sprintf("        .xin_data(%s_data), .xin_valid(%s_valid), .xin_sop(%s_sop),", xin, xin, xin))
			a(fmt.Sprintf("        .xin_eop(%s_eop), .xin_ready(%s_ready),", xin, xin))
			a(fmt.Sprintf("        .xin_vc(nob_%d_vc),", l))
			a(fmt.Sprintf("        .xout_data(t_%d_%d_data), .xout_valid(t_%d_%d_valid), .xout_sop(t_%d_%d_sop),", l, x, l, x, l, x))
			a(fmt.Sprintf("        .xout_eop(t_%d_%d_eop), .xout_ready(t_%d_%d_ready),", l, x, l, x))
			a(fmt.Sprintf("        .xout_vc(t_%d_%d_vc),", l, x))
			a(fmt.Sprintf("        .yout_data(y_%d_%d_0_data), .yout_valid(y_%d_%d_0_valid), .yout_sop(y_%d_%d_0_sop),", l, x, l, x, l, x))
			a(fmt.Sprintf("        .yout_eop(y_%d_%d_0_eop), .yout_ready(y_%d_%d_0_ready),", l, x, l, x))
			a(fmt.Sprintf("        .yout_vc(y_%d_%d_0_vc)", l, x))
			a("    );")
			if x == bx-1 {
				a("    // X-lane residual sink (must stay empty)")
				a(fmt.Sprintf("    assign xres_%d_data  = t_%d_%d_data;", l, l, x))
				a(fmt.Sprintf("    assign xres_%d_valid = t_%d_%d_valid;", l, l, x))
				a(fmt.Sprintf("    assign xres_%d_sop   = t_%d_%d_sop;", l, l, x))
				a(fmt.Sprintf("    assign xres_%d_eop   = t_%d_%d_eop;", l, l, x))
				a(fmt.Sprintf("    assign t_%d_%d_ready = 1'b1;", l, x))
			} else {
				a("    // X-lane repeater to next column")
				a(fmt.Sprintf("    hfr u_%d_hx_%d (", l, x))
				a(fmt.Sprintf("        .route_bitmap(11'h%03x),  // layer %d (board X-lane)", (l+1)<<7, l+1))
				a("        .clk(clk), .rst_n(rst_n),")
				a(fmt.Sprintf("        .in_data(t_%d_%d_data), .in_valid(t_%d_%d_valid), .in_sop(t_%d_%d_sop),", l, x, l, x, l, x))
				a(fmt.Sprintf("        .in_eop(t_%d_%d_eop), .in_ready(t_%d_%d_ready),", l, x, l, x))
				a(fmt.Sprintf("        .in_vc(t_%d_%d_vc),", l, x))
				a(fmt.Sprintf("        .out_data(h_%d_%d_data), .out_valid(h_%d_%d_valid), .out_sop(h_%d_%d_sop),", l, x, l, x, l, x))
				a(fmt.Sprintf("        .out_eop(h_%d_%d_eop), .out_ready(h_%d_%d_ready),", l, x, l, x))
				a(fmt.Sprintf("        .out_vc(h_%d_%d_vc)", l, x))
				a("    );")
			}
			a("")
		}

		for x := 0; x < bx; x++ {
			for y := 0; y < by; y++ {
				mid := (x << 4) | y
				yout := fmt.Sprintf("y_%d_%d_%d", l, x, y+1)
				if y == by-1 {
					yout = fmt.Sprintf("yres_%d_%d", l, x)
				}
				a(fmt.Sprintf("    // -- node (%d,%d,%d) eject: MODULE_ID 0x%02x --------", l, x, y, mid))
				a(fmt.Sprintf("    node_eject #(.LOCAL_MODULE(8'h%02x)) u_%d_%d_%d (", mid, l, x, y))
				a("        .clk(clk), .rst_n(rst_n),")
				a(fmt.Sprintf("        .yin_data(y_%d_%d_%d_data), .yin_valid(y_%d_%d_%d_valid), .yin_sop(y_%d_%d_%d_sop),", l, x, y, l, x, y, l, x, y))
				a(fmt.Sprintf("        .yin_eop(y_%d_%d_%d_eop), .yin_ready(y_%d_%d_%d_ready),", l, x, y, l, x, y))
				a(fmt.Sprintf("        .yin_vc(y_%d_%d_%d_vc),", l, x, y))
				a(fmt.Sprintf("        .yout_data(%s_data), .yout_valid(%s_valid), .yout_sop(%s_sop),", yout, yout, yout))
				a(fmt.Sprintf("        .yout_eop(%s_eop), .yout_ready(%s_ready),", yout, yout))
				a(fmt.Sprintf("        .yout_vc(y_%d_%d_%d_vc),", l, x, y+1))
				a(fmt.Sprintf("        .node_data(node_e_%d_%d_%d_data), .node_valid(node_e_%d_%d_%d_valid), .node_sop(node_e_%d_%d_%d_sop),", l, x, y, l, x, y, l, x, y))
				a(fmt.Sprintf("        .node_eop(node_e_%d_%d_%d_eop), .node_ready(node_e_%d_%d_%d_ready),", l, x, y, l, x, y))
				a(fmt.Sprintf("        .node_vc(node_vc_%d_%d_%d)", l, x, y))
				a("    );")
				k := biases[NodeID{L: l, X: x, Y: y}]
				a(fmt.Sprintf("    // -- node (%d,%d,%d) MAC stub: bias-add kernel K=%d ----", l, x, y, k))
				a(fmt.Sprintf("    pe_tile_stub #(.MULT_LATENCY(2), .KERNEL_CONST(8'h%02x)) u_pe_%d_%d_%d (", k, l, x, y))
				a("        .clk(clk), .rst_n(rst_n),")
				a(fmt.Sprintf("        .routing_bitmap(11'h%03x),  // layer %d, Y, +, dist %d", ((l+1)<<7)|(1<<6)|y, l+1, y))
				a(fmt.Sprintf("        .s_axis_tdata(node_e_%d_%d_%d_data), .s_axis_tvalid(node_e_%d_%d_%d_valid), .s_axis_tready(node_e_%d_%d_%d_ready),", l, x, y, l, x, y, l, x, y))
				a(fmt.Sprintf("        .s_axis_tlast(node_e_%d_%d_%d_eop), .s_axis_tstart(node_e_%d_%d_%d_sop),", l, x, y, l, x, y))
				a(fmt.Sprintf("        .m_axis_tdata(node_%d_%d_%d_data), .m_axis_tvalid(node_%d_%d_%d_valid), .m_axis_tready(node_%d_%d_%d_ready),", l, x, y, l, x, y, l, x, y))
				a(fmt.Sprintf("        .m_axis_tlast(node_%d_%d_%d_eop), .m_axis_tstart(node_%d_%d_%d_sop),", l, x, y, l, x, y))
				a(fmt.Sprintf("        .m_axis_tx_tdata(txe_%d_%d_%d_data), .m_axis_tx_tvalid(txe_%d_%d_%d_valid), .m_axis_tx_tready(txe_%d_%d_%d_ready),", l, x, y, l, x, y, l, x, y))
				a(fmt.Sprintf("        .m_axis_tx_tlast(txe_%d_%d_%d_eop), .m_axis_tx_tstart(txe_%d_%d_%d_sop),", l, x, y, l, x, y))
				a(fmt.Sprintf("        .tx_vc(txe_%d_%d_%d_vc),", l, x, y))
				a(fmt.Sprintf("        .route_err(), .corrupt_out(node_corrupt_%d_%d_%d)", l, x, y))
				a("    );")
			}
		}

		// -- board egress merge trees (node TX -> NoB upstream) ---------
		a(fmt.Sprintf("    // -- board %d egress merge: Y-up columns, then X-up ----", l))
		colWires := make([]string, bx)
		for x := 0; x < bx; x++ {
			col := fmt.Sprintf("txe_%d_%d_0", l, x)
			if by > 1 {
				for y := 0; y < by-1; y++ {
					prev := fmt.Sprintf("txe_%d_%d_%d", l, x, y)
					if y > 0 {
						prev = fmt.Sprintf("ym_%d_%d_%d", l, x, y-1)
					}
					a(fmt.Sprintf("    vc_merge u_%d_ym_%d_%d (", l, x, y))
					a("        .clk(clk), .rst_n(rst_n),")
					a(fmt.Sprintf("        .a_data(%s_data), .a_valid(%s_valid), .a_sop(%s_sop),", prev, prev, prev))
					a(fmt.Sprintf("        .a_eop(%s_eop), .a_ready(%s_ready), .a_vc(%s_vc),", prev, prev, prev))
					a(fmt.Sprintf("        .b_data(txe_%d_%d_%d_data), .b_valid(txe_%d_%d_%d_valid), .b_sop(txe_%d_%d_%d_sop),", l, x, y+1, l, x, y+1, l, x, y+1))
					a(fmt.Sprintf("        .b_eop(txe_%d_%d_%d_eop), .b_ready(txe_%d_%d_%d_ready), .b_vc(txe_%d_%d_%d_vc),", l, x, y+1, l, x, y+1, l, x, y+1))
					a(fmt.Sprintf("        .out_data(ym_%d_%d_%d_data), .out_valid(ym_%d_%d_%d_valid), .out_sop(ym_%d_%d_%d_sop),", l, x, y, l, x, y, l, x, y))
					a(fmt.Sprintf("        .out_eop(ym_%d_%d_%d_eop), .out_ready(ym_%d_%d_%d_ready), .out_vc(ym_%d_%d_%d_vc)", l, x, y, l, x, y, l, x, y))
					a("    );")
					col = fmt.Sprintf("ym_%d_%d_%d", l, x, by-2)
				}
			}
			colWires[x] = col
		}
		if bx > 1 {
			for xx := 0; xx < bx-1; xx++ {
				prev := colWires[xx]
				if xx > 0 {
					prev = fmt.Sprintf("xm_%d_%d", l, xx-1)
				}
				a(fmt.Sprintf("    vc_merge u_%d_xm_%d (", l, xx))
				a("        .clk(clk), .rst_n(rst_n),")
				a(fmt.Sprintf("        .a_data(%s_data), .a_valid(%s_valid), .a_sop(%s_sop),", prev, prev, prev))
				a(fmt.Sprintf("        .a_eop(%s_eop), .a_ready(%s_ready), .a_vc(%s_vc),", prev, prev, prev))
				bnxt := colWires[xx+1]
				a(fmt.Sprintf("        .b_data(%s_data), .b_valid(%s_valid), .b_sop(%s_sop),", bnxt, bnxt, bnxt))
				a(fmt.Sprintf("        .b_eop(%s_eop), .b_ready(%s_ready), .b_vc(%s_vc),", bnxt, bnxt, bnxt))
				a(fmt.Sprintf("        .out_data(xm_%d_%d_data), .out_valid(xm_%d_%d_valid), .out_sop(xm_%d_%d_sop),", l, xx, l, xx, l, xx))
				a(fmt.Sprintf("        .out_eop(xm_%d_%d_eop), .out_ready(xm_%d_%d_ready), .out_vc(xm_%d_%d_vc)", l, xx, l, xx, l, xx))
				a("    );")
			}
			a(fmt.Sprintf("    assign nobu_%d_data  = xm_%d_%d_data;", l, l, bx-2))
			a(fmt.Sprintf("    assign nobu_%d_valid = xm_%d_%d_valid;", l, l, bx-2))
			a(fmt.Sprintf("    assign nobu_%d_sop   = xm_%d_%d_sop;", l, l, bx-2))
			a(fmt.Sprintf("    assign nobu_%d_eop   = xm_%d_%d_eop;", l, l, bx-2))
			a(fmt.Sprintf("    assign xm_%d_%d_ready = nobu_%d_ready;", l, bx-2, l))
			a(fmt.Sprintf("    assign nobu_%d_vc    = xm_%d_%d_vc;", l, l, bx-2))
		} else {
			a(fmt.Sprintf("    assign nobu_%d_data  = %s_data;", l, colWires[0]))
			a(fmt.Sprintf("    assign nobu_%d_valid = %s_valid;", l, colWires[0]))
			a(fmt.Sprintf("    assign nobu_%d_sop   = %s_sop;", l, colWires[0]))
			a(fmt.Sprintf("    assign nobu_%d_eop   = %s_eop;", l, colWires[0]))
			a(fmt.Sprintf("    assign %s_ready = nobu_%d_ready;", colWires[0], l))
			a(fmt.Sprintf("    assign nobu_%d_vc    = %s_vc;", l, colWires[0]))
		}
		a("")
	}

	// -- up-spine HFRs: spup(l+1) -> hfr -> spup_in(l) --------------------
	for pos := len(layerIDs) - 2; pos >= 0; pos-- {
		up := layerIDs[pos+1]
		l := layerIDs[pos]
		a(fmt.Sprintf("    // -- spine ascent repeater (layer %d -> %d) --------------", up+1, l+1))
		a(fmt.Sprintf("    hfr u_up_hfr_%d (", up))
		a(fmt.Sprintf("        .route_bitmap(11'h%03x),  // layer %d (up-spine stage)", (up+1)<<7, up+1))
		a("        .clk(clk), .rst_n(rst_n),")
		a(fmt.Sprintf("        .in_data(spup_%d_data), .in_valid(spup_%d_valid), .in_sop(spup_%d_sop),", up, up, up))
		a(fmt.Sprintf("        .in_eop(spup_%d_eop), .in_ready(spup_%d_ready),", up, up))
		a(fmt.Sprintf("        .in_vc(spup_%d_vc),", up))
		a(fmt.Sprintf("        .out_data(uph_%d_data), .out_valid(uph_%d_valid), .out_sop(uph_%d_sop),", l, l, l))
		a(fmt.Sprintf("        .out_eop(uph_%d_eop), .out_ready(uph_%d_ready),", l, l))
		a(fmt.Sprintf("        .out_vc(uph_%d_vc)", l))
		a("    );")
		a("")
	}

	for _, l := range layerIDs {
		for x := 0; x < bx; x++ {
			a(fmt.Sprintf("    assign yres_%d_%d_ready = 1'b1;", l, x))
		}
	}

	a("endmodule")
	return out.String()
}

// pyIntList formats an int slice like Python's repr: "[0, 1, 2]".
func pyIntList(v []int) string {
	parts := make([]string, len(v))
	for i, n := range v {
		parts[i] = fmt.Sprintf("%d", n)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}
