// Haskell-to-PNM lowering: compiles FP64 IR into PNM dispatch instructions.
//
// Each FP64 operation maps to a node running an f64_* kernel. Operands are
// packed as big-endian FP64 bytes in token payloads. Results chain through
// nodes: the output of one operation becomes the input token of the next.
//
// Usage:
//
//	prog, _ := CompileHaskell(source)
//	pnm := LowerToPNM(prog, Dims{Layers: 2, Bx: 2, By: 2})
//	os.WriteFile("example.pnm", []byte(pnm), 0644)
package pnm

import (
	"fmt"
	"math"
	"sort"
	"strings"
)

// LowerToPNM compiles a Haskell program into a .pnm program string
// dispatchable on the given chassis dimensions.
//
// Mapping strategy:
//   - Each FP64 IR instruction → one node with the matching f64_* kernel
//   - Nodes are assigned round-robin across the chassis
//   - Operands are serialized as big-endian FP64 bytes (8 bytes each)
//   - For binary ops (add, mul, fma): 16 or 24 bytes payload
//   - Constants are pre-loaded as bias values on their target node
//   - Results chain: instruction N's result register feeds instruction N+1's input
func LowerToPNM(prog *FP64Program, dims Dims) string {
	return lowerFP64ToPNM(prog.Regs, dims)
}

// LowerHaskellToPNM compiles a Haskell program (with function definitions)
// into a .pnm program string.
func LowerHaskellToPNM(prog *HaskellProgram, dims Dims) string {
	var allInsts []FP64IR
	// Iterate in sorted name order so the emitted .pnm program (and the
	// round-robin node assignment) is deterministic across runs.
	names := make([]string, 0, len(prog.Funcs))
	for name := range prog.Funcs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		allInsts = append(allInsts, prog.Funcs[name].Body...)
	}
	allInsts = append(allInsts, prog.Regs...)
	return lowerFP64ToPNM(allInsts, dims)
}

// LowerHLSLToPNM compiles an HLSL program into a .pnm program string.
// HLSL uses FP32 ALU ops; values are packed as 8-byte payloads for the
// f64_* kernels (zero-extended float32 → float64).
func LowerHLSLToPNM(prog *HLSLProgram, dims Dims) string {
	var insts []FP64IR
	for _, inst := range prog.Regs {
		ir := FP64IR{
			Op:   hlslOpToFP64(inst.Op),
			Dest: inst.Dest,
			Src:  inst.Src,
			Cond: inst.Cond,
		}
		if inst.Op == ALUConst {
			ir.Imm = float64(inst.Imm)
		}
		if ir.Op == FP64Add && (inst.Op == ALULerp) {
			ir.Op = FP64Add
		}
		if ir.Op != 0 || inst.Op == ALUConst || inst.Op == ALUMov {
			insts = append(insts, ir)
		}
	}
	return lowerFP64ToPNM(insts, dims)
}

// hlslOpToFP64 maps an HLSL FP32 ALU opcode to the corresponding FP64 opcode.
func hlslOpToFP64(op FP32ALUOp) FP64Op {
	switch op {
	case ALUAdd:
		return FP64Add
	case ALUSub:
		return FP64Sub
	case ALUMul:
		return FP64Mul
	case ALUDiv:
		return FP64Div
	case ALUMin:
		return FP64Min
	case ALUMax:
		return FP64Max
	case ALUCmp:
		return FP64Cmp
	case ALUMov:
		return FP64Mov
	case ALUConst:
		return FP64Const
	default:
		return FP64Add // fallback
	}
}

func lowerFP64ToPNM(allInsts []FP64IR, dims Dims) string {
	totalNodes := dims.Layers * dims.Bx * dims.By
	if totalNodes == 0 {
		return "# error: empty chassis\n"
	}

	var b strings.Builder
	b.WriteString("# Generated by haskell_pnm — Haskell → PNM dispatch\n")
	fmt.Fprintf(&b, "# chassis: %dx%dx%d = %d nodes\n", dims.Layers, dims.Bx, dims.By, totalNodes)
	b.WriteString("#\n# Kernel mapping:\n")
	b.WriteString("#   f64_add: payload = [a:8bytes, b:8bytes] → result = a + b\n")
	b.WriteString("#   f64_mul: payload = [a:8bytes, b:8bytes] → result = a * b\n")
	b.WriteString("#   f64_fma: payload = [a:8bytes, b:8bytes, c:8bytes] → result = a*b + c\n")
	b.WriteString("#   f64_sub: payload = [a:8bytes, b:8bytes] → result = a - b\n")
	b.WriteString("#   f64_div: payload = [a:8bytes, b:8bytes] → result = a / b\n")
	b.WriteString("#   f64_min: payload = [a:8bytes, b:8bytes] → result = min(a, b)\n")
	b.WriteString("#   f64_max: payload = [a:8bytes, b:8bytes] → result = max(a, b)\n")
	b.WriteString("#   f64_neg: payload = [a:8bytes] → result = -a\n")
	b.WriteString("#   f64_cmp: payload = [a:8bytes, b:8bytes, op:2bytes] → result = 1.0/0.0\n")
	b.WriteString("#\n")

	if len(allInsts) == 0 {
		b.WriteString("# no operations to dispatch\n")
		return b.String()
	}

	// Assign nodes round-robin
	type nodeOp struct {
		node NodeID
		inst FP64IR
	}
	ops := make([]nodeOp, len(allInsts))
	nodeIdx := 0
	for i, inst := range allInsts {
		l := nodeIdx / (dims.Bx * dims.By)
		xy := nodeIdx % (dims.Bx * dims.By)
		x := xy / dims.By
		y := xy % dims.By
		ops[i] = nodeOp{
			node: NodeID{L: l % dims.Layers, X: x % dims.Bx, Y: y % dims.By},
			inst: inst,
		}
		nodeIdx++
	}

	// Emit kernel directives
	seen := map[NodeID]bool{}
	for _, op := range ops {
		kernel := irOpToKernel(op.inst.Op)
		if kernel == "" {
			continue
		}
		if seen[op.node] {
			continue
		}
		seen[op.node] = true
		b.WriteString(fmt.Sprintf("kernel %s %d %d %d\n", kernel, op.node.L, op.node.X, op.node.Y))
	}

	// Emit token directives (one per operation)
	for i, op := range ops {
		kernel := irOpToKernel(op.inst.Op)
		if kernel == "" {
			continue
		}
		payload := serializeOperands(op.inst)
		if len(payload) == 0 {
			continue
		}
		b.WriteString("token ")
		b.WriteString(fmt.Sprintf("%d %d %d  ", op.node.L, op.node.X, op.node.Y))
		for _, bt := range payload {
			fmt.Fprintf(&b, "%02x ", bt)
		}
		b.WriteString(fmt.Sprintf("  # op %d: %s\n", i, op.inst.Op))
	}

	return b.String()
}

// irOpToKernel maps an FP64 opcode to the corresponding PNM kernel name.
func irOpToKernel(op FP64Op) string {
	switch op {
	case FP64Add:
		return "f64_add"
	case FP64Mul:
		return "f64_mul"
	case FP64FMA:
		return "f64_fma"
	case FP64Sub:
		return "f64_sub"
	case FP64Div:
		return "f64_div"
	case FP64Min:
		return "f64_min"
	case FP64Max:
		return "f64_max"
	case FP64Neg:
		return "f64_neg"
	case FP64Cmp:
		return "f64_cmp"
	default:
		return "" // const, mov, etc. → handled via bias/inline
	}
}

// serializeOperands packs the source operands of an FP64 IR instruction
// into a byte payload (big-endian FP64 encoding).
func serializeOperands(inst FP64IR) []byte {
	switch inst.Op {
	case FP64Add, FP64Mul, FP64Sub, FP64Div, FP64Min, FP64Max:
		// Two FP64 operands: a + b, a * b, a - b, a / b, min(a,b), max(a,b)
		// We encode the register names as placeholders;
		// the actual values come from previous results
		// For now, use the immediate values if available
		return packFP64Args(inst)
	case FP64FMA:
		// Three FP64 operands: a*b + c
		return packFP64Args(inst)
	case FP64Neg:
		// One FP64 operand: -a
		return packFP64Args(inst)
	case FP64Cmp:
		// Two FP64 operands plus a 2-byte ASCII comparison code
		// ("==", "!=", "/=", "<", ">", "<=", ">=") in the payload tail.
		payload := packFP64Args(inst)
		op := inst.Cond
		if len(op) == 1 {
			op = op + " "
		}
		if len(op) > 2 {
			op = op[:2]
		}
		return append(payload, []byte(op)...)
	default:
		return nil
	}
}

// packFP64Args packs instruction arguments into 8-byte FP64 chunks.
// For register references, we encode a deterministic value based on the
// register name (the co-sim will substitute actual delivery results).
func packFP64Args(inst FP64IR) []byte {
	var result []byte
	for _, src := range inst.Src {
		result = append(result, fp64ToBytes(registerValue(src))...)
	}
	return result
}

// registerValue produces a deterministic FP64 value for a register name.
// This is a placeholder; in a real pipeline, register values would come
// from previous instruction results.
func registerValue(name string) float64 {
	// Hash the register name to produce a deterministic value
	var h uint64
	for _, c := range name {
		h = h*31 + uint64(c)
	}
	// Map to [1.0, 2.0) range for numerical stability
	return 1.0 + float64(h&0xFFFFFFFF)/float64(0xFFFFFFFF)
}

// EmitProgramString returns the full .pnm program for a Haskell source string.
func EmitProgramString(src string, dims Dims) (string, error) {
	prog, err := CompileHaskell(src)
	if err != nil {
		return "", fmt.Errorf("Haskell compilation failed: %w", err)
	}
	return LowerHaskellToPNM(prog, dims), nil
}

// EmitRProgramString returns the full .pnm program for an R source string.
func EmitRProgramString(src string, dims Dims) (string, error) {
	prog, err := CompileR(src)
	if err != nil {
		return "", fmt.Errorf("R compilation failed: %w", err)
	}
	return LowerToPNM(prog, dims), nil
}

// EmitHLSLProgramString returns the full .pnm program for an HLSL source string.
func EmitHLSLProgramString(src string, dims Dims) (string, error) {
	prog, err := CompileHLSL(src)
	if err != nil {
		return "", fmt.Errorf("HLSL compilation failed: %w", err)
	}
	return LowerHLSLToPNM(prog, dims), nil
}

// FormatFP64Payload formats a byte payload as a human-readable FP64 list.
func FormatFP64Payload(payload []byte) string {
	var vals []string
	for i := 0; i+8 <= len(payload); i += 8 {
		v := bytesToFP64(payload[i : i+8])
		vals = append(vals, fmt.Sprintf("%.4f", v))
	}
	return "[" + strings.Join(vals, ", ") + "]"
}

// FP64ToBytes exports fp64ToBytes for external use.
func FP64ToBytes(v float64) []byte {
	return fp64ToBytes(v)
}

// BytesToFP64 exports bytesToFP64 for external use.
func BytesToFP64(b []byte) float64 {
	return bytesToFP64(b)
}

// PackFP64Token creates a token payload from a slice of float64 values.
func PackFP64Token(values ...float64) []byte {
	var payload []byte
	for _, v := range values {
		payload = append(payload, fp64ToBytes(v)...)
	}
	return payload
}

// UnpackFP64Result extracts float64 values from a result payload.
func UnpackFP64Result(payload []byte) []float64 {
	var vals []float64
	for i := 0; i+8 <= len(payload); i += 8 {
		vals = append(vals, bytesToFP64(payload[i:i+8]))
	}
	return vals
}

// Unused import guard
var _ = math.Float64frombits
