#!/usr/bin/env python3
"""Generate pnm_top.v — the paper topology wired from the HDL fabric blocks.

Mirrors Paper.MD §2.1–2.2:

  * a single vertical spine of z_ingress gates (LAYER_ID compare), each
    stage HFR-repeatered
  * a thin X/Y board per layer, hung off the spine via the ingress NoB port
  * dimension-order on-board routing: an X-lane of xy_turn gates; every
    column drops onto a Y-lane of node_eject gates
  * every (layer, x, y) node DMA port is exposed so Python virtual execution
    units can attach to the real hardware

Usage:
    python3 gen_topology.py                 # defaults: 3 layers x 4 x 4 = 48 nodes
    python3 gen_topology.py -l 8 -x 8 -y 8  # the 512-node reference chassis

Also writes pnm_top_params.py so the Python side matches the config.
"""
from __future__ import annotations

import argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent


def _module_id(x: int, y: int) -> int:
    return (x << 4) | y


def gen(layer_ids: list, bx: int, by: int) -> str:
    """Generate pnm_top for the given layers.

    layer_ids: global (0-based) layer numbers to instantiate, in spine order.
    A sub-list generates a horizontal slice of the chassis -- used by
    run.py --groups to simulate layer groups in parallel vvp processes.
    """
    out: list[str] = []
    a = out.append
    nodes = len(layer_ids) * bx * by

    # ── port list ──────────────────────────────────────────────────────
    ports: list[str] = [
        "    input  wire       clk,",
        "    input  wire       rst_n,",
        "",
        "    // -- spine injection (AOT compiler / scheduler) ------------",
        "    input  wire [7:0] inject_data,",
        "    input  wire       inject_valid,",
        "    input  wire       inject_sop,",
        "    input  wire       inject_eop,",
        "    output wire       inject_ready,",
        "",
        "    // -- spine tail (non-local traffic passes straight through) -",
        "    output wire [7:0] tail_data,",
        "    output wire       tail_valid,",
        "    output wire       tail_sop,",
        "    output wire       tail_eop,",
        "",
        "    // -- node DMA ports (virtual execution units) --------------",
    ]
    for l in layer_ids:
        for x in range(bx):
            for y in range(by):
                p = f"node_{l}_{x}_{y}"
                ports += [
                    f"    output wire [7:0] {p}_data,",
                    f"    output wire       {p}_valid,",
                    f"    output wire       {p}_sop,",
                    f"    output wire       {p}_eop,",
                    f"    input  wire       {p}_ready,",
                ]
    ports += [
        "",
        "    // -- board residual lanes (must stay empty) ----------------",
        "    //    yres_<l>_<x> : tail of column x's Y-lane after last row",
    ]
    for l in layer_ids:
        for x in range(bx):
            p = f"yres_{l}_{x}"
            ports += [
                f"    output wire [7:0] {p}_data,",
                f"    output wire       {p}_valid,",
                f"    output wire       {p}_sop,",
                f"    output wire       {p}_eop,",
            ]
    ports += ["    //    xres_<l> : tail of board l's X-lane after last column"]
    for l in layer_ids:
        p = f"xres_{l}"
        ports += [
            f"    output wire [7:0] {p}_data,",
            f"    output wire       {p}_valid,",
            f"    output wire       {p}_sop,",
            f"    output wire       {p}_eop,",
        ]
    ports[-1] = ports[-1].rstrip(",")  # last port carries no comma

    # ── header ──────────────────────────────────────────────────────────
    a('`include "pnm_defs.vh"')
    a("")
    a("// AUTO-GENERATED by sim/gen_topology.py -- do not edit by hand.")
    a(f"// layers={layer_ids}  board_x={bx}  board_y={by}  nodes={nodes}")
    a("//")
    a("// Architecture (Paper.MD §2.1–2.2):")
    a("//   single-spine tree fabric: z_ingress (LAYER_ID compare) repeatered by HFR")
    a("//   on-board dimension-order: X-lane of xy_turn gates -> Y-lanes of node_eject")
    a("//   every (layer, x, y) ejects to a node DMA / virtual execution unit port")
    a("module pnm_top (")
    a("\n".join(ports))
    a(");")
    a("")
    a("    // ================= spine =================================")
    a("    // each stage: ingress compares LAYER_ID; HFR repeats the pass path")

    for l in layer_ids:
        a(f"    wire [7:0] sp_{l}_data;  wire sp_{l}_valid, sp_{l}_sop, sp_{l}_eop, sp_{l}_ready;")
        a(f"    wire [7:0] q_{l}_data;   wire q_{l}_valid,  q_{l}_sop,  q_{l}_eop,  q_{l}_ready;")
        a(f"    wire [7:0] nob_{l}_data; wire nob_{l}_valid, nob_{l}_sop, nob_{l}_eop, nob_{l}_ready;")
    a("")

    for pos, l in enumerate(layer_ids):
        spin = "inject" if pos == 0 else f"q_{layer_ids[pos-1]}"
        a(f"    // -- layer {l} ingress (strips LAYER_ID on match) -----------")
        a(f"    z_ingress #(.LOCAL_LAYER(8'h{l+1:02x})) u_ing_{l} (")
        a("        .clk(clk), .rst_n(rst_n),")
        a(f"        .spin_data({spin}_data), .spin_valid({spin}_valid), .spin_sop({spin}_sop),")
        a(f"        .spin_eop({spin}_eop), .spin_ready({spin}_ready),")
        a(f"        .spout_data(sp_{l}_data), .spout_valid(sp_{l}_valid), .spout_sop(sp_{l}_sop),")
        a(f"        .spout_eop(sp_{l}_eop), .spout_ready(sp_{l}_ready),")
        a(f"        .nob_data(nob_{l}_data), .nob_valid(nob_{l}_valid), .nob_sop(nob_{l}_sop),")
        a(f"        .nob_eop(nob_{l}_eop), .nob_ready(nob_{l}_ready)")
        a("    );")
        a(f"    // -- spine repeater {l} --------------------------------------")
        a(f"    hfr u_sp_hfr_{l} (")
        a("        .clk(clk), .rst_n(rst_n),")
        a(f"        .in_data(sp_{l}_data), .in_valid(sp_{l}_valid), .in_sop(sp_{l}_sop),")
        a(f"        .in_eop(sp_{l}_eop), .in_ready(sp_{l}_ready),")
        a(f"        .out_data(q_{l}_data), .out_valid(q_{l}_valid), .out_sop(q_{l}_sop),")
        a(f"        .out_eop(q_{l}_eop), .out_ready(q_{l}_ready)")
        a("    );")
        a("")

    last = layer_ids[-1]
    a("    // -- spine tail -----------------------------------------------")
    a(f"    assign tail_data  = q_{last}_data;")
    a(f"    assign tail_valid = q_{last}_valid;")
    a(f"    assign tail_sop   = q_{last}_sop;")
    a(f"    assign tail_eop   = q_{last}_eop;")
    a(f"    assign q_{last}_ready = 1'b1;")
    a("")

    # ── boards ──────────────────────────────────────────────────────────
    for l in layer_ids:
        a(f"    // ================= board {l} (layer {l+1}) ==============")
        a("    // dimension-order routing: X first, then Y.")
        for x in range(bx):
            a(f"    wire [7:0] t_{l}_{x}_data; wire t_{l}_{x}_valid, t_{l}_{x}_sop, t_{l}_{x}_eop, t_{l}_{x}_ready;")
            a(f"    wire [7:0] h_{l}_{x}_data; wire h_{l}_{x}_valid, h_{l}_{x}_sop, h_{l}_{x}_eop, h_{l}_{x}_ready;")
            for y in range(by):
                a(f"    wire [7:0] y_{l}_{x}_{y}_data; wire y_{l}_{x}_{y}_valid, y_{l}_{x}_{y}_sop, y_{l}_{x}_{y}_eop, y_{l}_{x}_{y}_ready;")
            if l == layer_ids[-1]:
                a(f"    wire yres_{l}_{x}_ready;")
        a("")

        for x in range(bx):
            xin = f"nob_{l}" if x == 0 else f"h_{l}_{x-1}"
            a(f"    // -- column {x}: X->Y turn gate ---------------------------")
            a(f"    xy_turn #(.LOCAL_X(4'h{x:x})) u_{l}_turn_{x} (")
            a("        .clk(clk), .rst_n(rst_n),")
            a(f"        .xin_data({xin}_data), .xin_valid({xin}_valid), .xin_sop({xin}_sop),")
            a(f"        .xin_eop({xin}_eop), .xin_ready({xin}_ready),")
            a(f"        .xout_data(t_{l}_{x}_data), .xout_valid(t_{l}_{x}_valid), .xout_sop(t_{l}_{x}_sop),")
            a(f"        .xout_eop(t_{l}_{x}_eop), .xout_ready(t_{l}_{x}_ready),")
            a(f"        .yout_data(y_{l}_{x}_0_data), .yout_valid(y_{l}_{x}_0_valid), .yout_sop(y_{l}_{x}_0_sop),")
            a(f"        .yout_eop(y_{l}_{x}_0_eop), .yout_ready(y_{l}_{x}_0_ready)")
            a("    );")
            if x == bx - 1:
                a(f"    // X-lane residual sink (must stay empty)")
                a(f"    assign xres_{l}_data  = t_{l}_{x}_data;")
                a(f"    assign xres_{l}_valid = t_{l}_{x}_valid;")
                a(f"    assign xres_{l}_sop   = t_{l}_{x}_sop;")
                a(f"    assign xres_{l}_eop   = t_{l}_{x}_eop;")
                a(f"    assign t_{l}_{x}_ready = 1'b1;")
            else:
                a(f"    // X-lane repeater to next column")
                a(f"    hfr u_{l}_hx_{x} (")
                a("        .clk(clk), .rst_n(rst_n),")
                a(f"        .in_data(t_{l}_{x}_data), .in_valid(t_{l}_{x}_valid), .in_sop(t_{l}_{x}_sop),")
                a(f"        .in_eop(t_{l}_{x}_eop), .in_ready(t_{l}_{x}_ready),")
                a(f"        .out_data(h_{l}_{x}_data), .out_valid(h_{l}_{x}_valid), .out_sop(h_{l}_{x}_sop),")
                a(f"        .out_eop(h_{l}_{x}_eop), .out_ready(h_{l}_{x}_ready)")
                a("    );")
            a("")

        for x in range(bx):
            for y in range(by):
                mid = _module_id(x, y)
                if y < by - 1:
                    yout = f"y_{l}_{x}_{y+1}"
                else:
                    yout = f"yres_{l}_{x}"
                a(f"    // -- node ({l},{x},{y}) eject: MODULE_ID 0x{mid:02x} --------")
                a(f"    node_eject #(.LOCAL_MODULE(8'h{mid:02x})) u_{l}_{x}_{y} (")
                a("        .clk(clk), .rst_n(rst_n),")
                a(f"        .yin_data(y_{l}_{x}_{y}_data), .yin_valid(y_{l}_{x}_{y}_valid), .yin_sop(y_{l}_{x}_{y}_sop),")
                a(f"        .yin_eop(y_{l}_{x}_{y}_eop), .yin_ready(y_{l}_{x}_{y}_ready),")
                a(f"        .yout_data({yout}_data), .yout_valid({yout}_valid), .yout_sop({yout}_sop),")
                a(f"        .yout_eop({yout}_eop), .yout_ready({yout}_ready),")
                a(f"        .node_data(node_{l}_{x}_{y}_data), .node_valid(node_{l}_{x}_{y}_valid), .node_sop(node_{l}_{x}_{y}_sop),")
                a(f"        .node_eop(node_{l}_{x}_{y}_eop), .node_ready(node_{l}_{x}_{y}_ready)")
                a("    );")
        a("")

    for l in layer_ids:
        for x in range(bx):
            a(f"    assign yres_{l}_{x}_ready = 1'b1;")

    a("endmodule")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-l", "--layers", type=int, default=3, help="spine layers / boards")
    ap.add_argument("-x", "--board-x", type=int, default=4, help="X columns per board")
    ap.add_argument("-y", "--board-y", type=int, default=4, help="Y rows per board")
    args = ap.parse_args()

    v = gen(list(range(args.layers)), args.board_x, args.board_y)
    (HERE / "pnm_top.v").write_text(v, encoding="utf-8")
    (HERE / "pnm_top_params.py").write_text(
        "# AUTO-GENERATED by sim/gen_topology.py -- do not edit by hand.\n"
        f"LAYERS = {args.layers}\n"
        f"BOARD_X = {args.board_x}\n"
        f"BOARD_Y = {args.board_y}\n"
        f"NODES = {args.layers * args.board_x * args.board_y}\n",
        encoding="utf-8",
    )
    print(f"wrote pnm_top.v ({args.layers}x{args.board_x}x{args.board_y} = "
          f"{args.layers * args.board_x * args.board_y} nodes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
