#!/usr/bin/env python3
"""Generate tb_pnm.v -- a self-checking Verilog testbench for pnm_top.

Where cocotb-style co-simulation would need a compiled Python bridge (which
fights with nix/uv Python installs), this testbench is the pure-Verilog half
of the co-simulation contract instead:

  * the tb reads the injection program from stimulus.hex ($readmemh) and
    streams it into the real fabric with valid/ready flow control at up to
    1 byte/cycle (Paper.MD §2.8: one routing decision per clock)
  * every node DMA sink applies deterministic backpressure (ready one cycle
    in N), proving the fabric is lossless, not dropping
  * every byte the fabric delivers -- node DMA ports, spine tail, and the
    X/Y-lane residual lanes -- is logged to delivery.log, stamped with the
    simulation cycle, so the Python side can verify byte-exact delivery,
    run the virtual execution units, and check per-packet latency against
    the paper's closed-form bound (§2.5, §3.4)

Simulation stops adaptively when the fabric has been quiet for 200 cycles,
so no fixed drain window has to be tuned by hand.
"""
from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent


def _module_id(x: int, y: int) -> int:
    return (x << 4) | y


def gen(layer_ids: list, bx: int, by: int, bp: dict, nbytes: int,
        stim: str = "stimulus.hex", log: str = "delivery.log") -> str:
    """Generate the testbench for the given layers.

    layer_ids must match the pnm_top.v under test (a sub-list = one slice
    of a chassis partitioned by run.py --groups).  stim/log are the
    $readmemh / $fopen file names, parameterized so parallel groups never
    share files.
    """
    out: list[str] = []
    a = out.append

    a("`timescale 1ns/1ps")
    a('`include "pnm_defs.vh"')
    a("")
    a("// AUTO-GENERATED by sim/gen_tb.py -- do not edit by hand.")
    a(f"// layers={layer_ids}  board_x={bx}  board_y={by}")
    a("//")
    a("// Pure-Verilog co-simulation harness for pnm_top.v:")
    a("//   * stimulus.hex ($readmemh) -> injector task -> real fabric")
    a("//   * per-node backpressure (ready 1 cycle in N) -> losslessness")
    a("//   * delivery.log records every node DMA / tail / residual byte")
    a("//   * $finish when the fabric has been quiet for 200 cycles")
    a("module tb_pnm;")
    a("")
    a("    // -- clock / reset -------------------------------------------")
    a("    reg clk = 1'b0;")
    a("    always #5 clk = ~clk; // 100 MHz")
    a("    reg rst_n = 1'b0;")
    a("")
    a("    // -- spine inject ---------------------------------------------")
    a("    reg  [7:0] inject_data = 8'h00;")
    a("    reg        inject_valid = 1'b0;")
    a("    reg        inject_sop = 1'b0;")
    a("    reg        inject_eop = 1'b0;")
    a("    wire       inject_ready;")
    a("")
    a("    // -- free-running cycle counter (timestamps delivery.log) ---")
    a("    reg  [31:0] cyc = 32'd0;")
    a("    always @(posedge clk) cyc <= cyc + 32'd1;")
    a("")
    a("    // -- spine tail / residual lanes ------------------------------")
    a("    wire [7:0] tail_data;  wire tail_valid, tail_sop, tail_eop;")
    for l in layer_ids:
        a(f"    wire [7:0] xres_{l}_data;  wire xres_{l}_valid, xres_{l}_sop, xres_{l}_eop;")
        for x in range(bx):
            a(f"    wire [7:0] yres_{l}_{x}_data;  wire yres_{l}_{x}_valid, yres_{l}_{x}_sop, yres_{l}_{x}_eop;")
    a("")
    a("    // -- node DMA ports -------------------------------------------")
    for l in layer_ids:
        for x in range(bx):
            for y in range(by):
                p = f"node_{l}_{x}_{y}"
                a(f"    wire [7:0] {p}_data;  wire {p}_valid, {p}_sop, {p}_eop;  reg {p}_ready;")
    a("")
    a("    // -- DUT: the paper-mirroring topology ------------------------")
    a("    pnm_top dut (")
    a("        .clk(clk), .rst_n(rst_n),")
    a("        .inject_data(inject_data), .inject_valid(inject_valid),")
    a("        .inject_sop(inject_sop), .inject_eop(inject_eop), .inject_ready(inject_ready),")
    a("        .tail_data(tail_data), .tail_valid(tail_valid),")
    a("        .tail_sop(tail_sop), .tail_eop(tail_eop),")
    conn: list[str] = []
    for l in layer_ids:
        for x in range(bx):
            for y in range(by):
                p = f"node_{l}_{x}_{y}"
                conn.append(f"        .{p}_data({p}_data), .{p}_valid({p}_valid), "
                            f".{p}_sop({p}_sop), .{p}_eop({p}_eop), .{p}_ready({p}_ready),")
    for l in layer_ids:
        for x in range(bx):
            p = f"yres_{l}_{x}"
            conn.append(f"        .{p}_data({p}_data), .{p}_valid({p}_valid), "
                        f".{p}_sop({p}_sop), .{p}_eop({p}_eop),")
    for l in layer_ids:
        p = f"xres_{l}"
        conn.append(f"        .{p}_data({p}_data), .{p}_valid({p}_valid), "
                    f".{p}_sop({p}_sop), .{p}_eop({p}_eop),")
    conn[-1] = conn[-1].rstrip(",")  # last port carries no comma
    a("\n".join(conn))
    a("    );")
    a("")
    a("    // -- per-node backpressure: ready 1 cycle in N ----------------")
    for l in layer_ids:
        for x in range(bx):
            for y in range(by):
                d = bp.get((l, x, y), 1)
                p = f"node_{l}_{x}_{y}"
                a(f"    reg [3:0] bpctr_{l}_{x}_{y};")
                a(f"    always @(posedge clk or negedge rst_n)")
                a(f"        if (!rst_n) bpctr_{l}_{x}_{y} <= 4'd0;")
                a(f"        else         bpctr_{l}_{x}_{y} <= bpctr_{l}_{x}_{y} + 4'd1;")
                a(f"    always @(*) {p}_ready = (bpctr_{l}_{x}_{y} % 4'd{d} == 4'd0);")
    a("")
    a("    // -- delivery log (cycle-stamped) ---------------------------")
    a('    integer fd;')
    a(f'    initial fd = $fopen("{log}", "w");')
    a("    always @(posedge clk)")
    a("        if (inject_valid && inject_ready)")
    a('            $fwrite(fd, "I %0d %0d %0d %0d\\n", cyc, inject_data, inject_sop, inject_eop);')
    for l in layer_ids:
        a(f"    always @(posedge clk)")
        a(f"        if (xres_{l}_valid)")
        a(f'            $fwrite(fd, "X %0d {l} %0d %0d %0d\\n", cyc, xres_{l}_data, xres_{l}_sop, xres_{l}_eop);')
        for x in range(bx):
            a(f"    always @(posedge clk)")
            a(f"        if (yres_{l}_{x}_valid)")
            a(f'            $fwrite(fd, "Y %0d {l} {x} %0d %0d %0d\\n", cyc, yres_{l}_{x}_data, yres_{l}_{x}_sop, yres_{l}_{x}_eop);')
    for l in layer_ids:
        for x in range(bx):
            for y in range(by):
                p = f"node_{l}_{x}_{y}"
                a(f"    always @(posedge clk)")
                a(f"        if ({p}_valid && {p}_ready)")
                a(f'            $fwrite(fd, "N %0d {l} {x} {y} %0d %0d %0d\\n", cyc, {p}_data, {p}_sop, {p}_eop);')
    a("    always @(posedge clk)")
    a("        if (tail_valid)")
    a('            $fwrite(fd, "T %0d %0d %0d %0d\\n", cyc, tail_data, tail_sop, tail_eop);')
    a("")
    a("    // -- injection program ($readmemh) ----------------------------")
    a(f"    parameter integer NBYTES = {nbytes};")
    a("    // stim[i][7:0] = byte, [8] = sop, [9] = eop")
    a("    reg [9:0] stim [0:(NBYTES > 0 ? NBYTES : 1)-1];")
    a(f'    initial $readmemh("{stim}", stim);')
    a("")
    a("    // Streaming injector: sustains 1 byte/cycle while the fabric")
    a("    // accepts (Paper.MD §2.8: one routing decision per clock).  Drive")
    a("    // at negedge, handshake at posedge; when !ready the byte is held.")
    a("    task inject_stream;")
    a("        integer i;")
    a("        begin")
    a("            i = 0;")
    a("            @(negedge clk);")
    a("            while (i < NBYTES) begin")
    a("                inject_data  = stim[i][7:0];")
    a("                inject_sop   = stim[i][8];")
    a("                inject_eop   = stim[i][9];")
    a("                inject_valid = 1'b1;")
    a("                @(posedge clk);")
    a("                if (inject_ready) i = i + 1;")
    a("                @(negedge clk);")
    a("            end")
    a("            inject_valid = 1'b0; inject_sop = 1'b0; inject_eop = 1'b0;")
    a("        end")
    a("    endtask")
    a("")
    a("    // -- adaptive termination --------------------------------------")
    a("    wire any_valid = inject_valid || tail_valid")
    for l in layer_ids:
        a(f"                    || xres_{l}_valid")
        for x in range(bx):
            a(f"                    || yres_{l}_{x}_valid")
    for l in layer_ids:
        for x in range(bx):
            for y in range(by):
                a(f"                    || node_{l}_{x}_{y}_valid")
    a("                    ;")
    a("")
    a("    reg inject_finished = 1'b0;")
    a("    reg [31:0] quiet = 32'd0;")
    a("    always @(posedge clk or negedge rst_n)")
    a("        if (!rst_n)          quiet <= 32'd0;")
    a("        else if (any_valid)  quiet <= 32'd0;")
    a("        else if (inject_finished) quiet <= quiet + 32'd1;")
    a("")
    a("    // ==============================================================")
    a("    initial begin")
    a("        repeat (5) @(negedge clk);")
    a("        rst_n = 1'b1;")
    a("        repeat (3) @(negedge clk);")
    a("")
    a("        inject_stream();")
    a("        inject_finished = 1'b1;")
    a("    end")
    a("")
    a("    initial begin")
    a("        wait (inject_finished === 1'b1);")
    a("        while (quiet < 32'd200) @(posedge clk);")
    a("        $fclose(fd);")
    a("        $display(\"=== SIM COMPLETE (quiet=%0d cycles) ===\", quiet);")
    a("        $finish;")
    a("    end")
    a("")
    a("    initial begin")
    a(f"        repeat ({64} * NBYTES + 1000000) @(negedge clk); // adaptive watchdog")
    a('        $display("=== WATCHDOG TIMEOUT ===");')
    a("        $fclose(fd);")
    a("        $finish;")
    a("    end")
    a("")
    a("endmodule")
    return "\n".join(out) + "\n"
